# Week 2--The basics of Python


- Module 2 covers python basics
    - Notes (Current page)
    - Youtube video

## I.1 Running Python

### I.1.1 Anaconda
- Anaconda downloads python and jupyter notebook (you are currently viewing a jupyter notebook)
- [Link](https://www.anaconda.com/products/individual)

### I.1.2 UV (for advanced users)
- UV downloads python and allows for version control
- [Link](v/getting-started/installation/)

### I.1.3 Binder (for beginners)
- Use binder by clicking on the binder button on our course homepage: https://mybinder.org/v2/gh/Data-Science-Public-Policy/graspp_2025_spring/HEAD

<img src="Screenshots/binder.png" />

# 2. Where is this notebook? Where is my Data? 


### IMPORTANT: If you are running on google colab you need to drag the csv file into your workspace
###

## 2.1 `File path`: fancy way to say the current folder you are working from

### 2.1.A Current folder

In [1]:
# Current path
import os
# os.getcwd(): Shows current folder this notebook is in
os.getcwd()

'/Users/sheena/Documents/GitHub/datascience-publicpolicy-2026/notebooks/week_2'

In [5]:
# This shows the files in the folder two folders above the current folder
os.listdir("../..")

['requirements.txt',
 'uv.lock',
 'environment.yml',
 'pyproject.toml',
 'README.md',
 '.gitignore',
 '.venv',
 '.git',
 'data',
 'notebooks',
 'src']

In [23]:
# This shows the files in the data/examples folder
os.listdir("../../data/examples/week_2")

['world_bank_data.csv']

### 2.1.1 Saving data: In this case words (a.k.a. a string)

In [30]:
# In python if you write a name (without spaces) and you write something on the right hand side this saves data/information
file_location = "../../data/examples/week_2/"
file_location

'../../data/examples/week_2/'

In [26]:
# This line saves the web address (URL) of the World Bank data file as text in a variable named 'url'.
url = "https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv"

In [27]:
# This line prints the url
url

'https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv'

# 3. Importing Data

## 3.1 Importing data (csv, excel, stata) to the notebook

In [22]:
os.listdir(file_location)

['world_bank_data.csv']

### 3.1.1 Import

In [19]:
import pandas as pd
saveddata = pd.read_csv("../../data/examples/week_2/world_bank_data.csv")
#saveddata

### 3.1.2 Import and save to notebook (same concept as 1.1.1)

In [32]:
file_location = "../../data/examples/week_2/world_bank_data.csv"
df = pd.read_csv(file_location)

### 3.1.3 Exploring the Data
Now that the data is loaded, let's take a peek at it. We can look at the top (`head`), the bottom (`tail`), and get a summary (`info`).

In [35]:
df.head(5)

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808

In [36]:
df.tail(2)

,Unnamed: 0,indicator,country,countryiso3code,date,value
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360
11,11,GDP per capita (current US$),United States,USA,2021,71318.307359

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12 non-null     int64
 1   indicator        12 non-null     object
 2   country          12 non-null     object
 3   countryiso3code  12 non-null     object
 4   date             12 non-null     int64
 5   value            12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes

## 3.2 Importing data from github

### 3.2.1 Importing the data

In [38]:
# This line saves the web address (URL) of the World Bank data file as text in a variable named 'url'.
url = "https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv"

# This line uses the pandas library's 'read_csv' function.
# A DataFrame is essentially a Python version of an Excel spreadsheet, a two-dimensional table with rows and columns.
import pandas as pd
df = pd.read_csv(url)

# The 'head(2)' returns the first 2 rows of the DataFrame.
df.head(2)

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176

In [8]:
# This line does the exact same thing as the previous line, but it directly uses the URL string, instead of the variable 'url'.
# It reads the World Bank data from the given URL and stores it as a pandas DataFrame named 'df'.
df = pd.read_csv("https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv")

# The 'head(3)' returns the first 3 rows of the DataFrame.
df.head(3)

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169

## 3.3 Importing data via an API

### 3.3.A Introducing functions

In [43]:
# We already used functions!

# function to read csvs from the pandas library
# pd.read_csv()
# function to read html from the pandas library
# pd.read_html()

#### 3.3.A.1 Basic function

In [40]:
# Now we make our own
def num_print(a):
    return a

def sheena_tool(part_1):
    return part_1

sheena_tool(3)

3

In [41]:
num_print(8)

8

In [42]:
num_print(7)

7

#### 3.3.A.2 Multiple arguments

In [45]:
def add_func(a,b,c):
    print('This function adds')
    final = a+b+c
    return final

def multiple_things(thing_1, thing_2):
    print(thing_1, thing_2)

In [14]:
add_func(10,20,10)

This function adds

40

### 3.3.1 Function to download data from the world bank WDI

### Just trust me for now!
Don't worry if the code block below looks like an alien language. We are defining a custom function to grab web data. Just execute the cell to see the data, and we will break down exactly how variables and data types work in the next notebook.

In [62]:
import requests
import pandas as pd
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    # Use io.BytesIO to pass the bytes content as a file-like object to read_xml
    df = pd.read_xml(io.BytesIO(response.content))
    return df

In [71]:
# Example 1
data = download_worldbank(
    indicator = 'NY.GDP.PCAP.CD' , 
    countries = ['AUS'],  
    date_start = '2010', 
    date_end = '2024'
)
data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2023,65058.377315,NaN,NaN,1

In [70]:
data

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2023,65058.377315,NaN,NaN,1
2,GDP per capita (current US$),Australia,AUS,2022,65169.519112,NaN,NaN,1
3,GDP per capita (current US$),Australia,AUS,2021,60758.904440,NaN,NaN,1
4,GDP per capita (current US$),Australia,AUS,2020,51983.452367,NaN,NaN,1
5,GDP per capita (current US$),Australia,AUS,2019,55194.758510,NaN,NaN,1
6,GDP per capita (current US$),Australia,AUS,2018,57410.173735,NaN,NaN,1
7,GDP per capita (current US$),Australia,AUS,2017,54117.547719,NaN,NaN,1
8,GDP per capita (current US$),Australia,AUS,2016,50084.444061,NaN,NaN,1
9,GDP per capita (current US$),Australia,AUS,2015,56970.361303,NaN,NaN,1

### What is a List? 
To tell the API which countries we want, we need to pass it multiple items using a **List**...

#### Lists syntax

- Lists can be made up of strings or numbers
- Spacing is not necessarily important!

In [74]:
import requests
import pandas as pd
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    # Use io.BytesIO to pass the bytes content as a file-like object to read_xml
    df = pd.read_xml(io.BytesIO(response.content))
    return df


# Example 2: Using saved objects
indicator_code = 'SP.POP.TOTL'  # Example: Total population
country_list = ['AUS'] # France, Germany, Italy
start_year = '2020'
end_year = '2022'

data2 = download_worldbank(
    indicator=indicator_code,
    countries=country_list,
    date_start=start_year,
    date_end=end_year
)
data2.head(2)

indicator_code = 'SP.POP.TOTL'  # Example: Total population
data1 = download_worldbank(
    indicator=indicator_code,
    countries=country_list,
    date_start=start_year,
    date_end=end_year
)
data1.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Australia,AUS,2022,26018721,NaN,NaN,0
1,"Population, total",Australia,AUS,2021,25685412,NaN,NaN,0

In [75]:
my_list = ['Python', 'R', 'Stata', 'Excel']

my_list

['Python', 'R', 'Stata', 'Excel']

In [76]:
listiswhatever = [1,2,3]

In [78]:
my_list = [3, 
           5,
           9,
           11]
type(indicator_code)

str

In [79]:
# Example 2: Using saved objects
indicator_code = 'SP.POP.TOTL'  # Example: Total population
country_list = ['FR', 'DE', 'IT'] # France, Germany, Italy
start_year = '2020'
end_year = '2022'

data2 = download_worldbank(
    indicator=indicator_code,
    countries=country_list,
    date_start=start_year,
    date_end=end_year
)
data2.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Germany,DEU,2022,83177813,NaN,NaN,0
1,"Population, total",Germany,DEU,2021,83196078,NaN,NaN,0